{var samples = {
	capitals: [
        {key:'de angst', value: 'de angst'},
        {key:'langzaam', value: 'langzaam'},
        {key:'de tong', value: 'de tong'},
        {key:'hij brengt', value: 'hij brengt'},
        {key:'hij vangt', value: 'hij vangt'},
        {key:'dankbaar', value: 'dankbaar'},
        {key:'hij bedankt', value: 'hij bedankt'},
        {key:'hij bedenkt', value: 'hij bedenkt'},
        {key:'hij drinkt', value: 'hij drinkt'},
        {key:'het stinkt', value: 'het stinkt'},
        {key:'samenstellingen', value: 'samenstellingen'},
        {key:'de afspraak', value: 'de afspraak'},
        {key:'de afwas', value: 'de afwas'},
        {key:'daarom', value: 'daarom'},
        {key:'erin', value: 'erin'},
        {key:'de koelkast', value: 'de koelkast'},
        {key:'omdat', value: 'omdat'},
        {key:'de rookworst', value: 'de rookworst'},
        {key:'de slagroom', value: 'de slagroom'},
        {key:'de steelpan', value: 'de steelpan'},
        {key:'de zondag', value: 'de zondag'},
        {key:'ei', value: 'ei'},
        {key:'klein', value: 'klein'},
        {key:'de trein', value: 'de trein'},
        {key:'het zeil', value: 'het zeil'},
        {key:'hij reist', value: 'hij reist'},
        {key:'hij zei', value: 'hij zei'},
        {key:'ij', value: 'ij'},
        {key:'de buikpijn', value: 'de buikpijn'},
        {key:'gelijk', value: 'gelijk'},
        {key:'het ontbijt', value: 'het ontbijt'},
        {key:'vijftien', value: 'vijftien'},
        {key:'hij bijt', value: 'hij bijt'},
        {key:'alweer', value: 'alweer'},
        {key:'veertien', value: 'veertien'},
        {key:'de voorkant', value: 'de voorkant'},
        {key:'de zeurpiet', value: 'de zeurpiet'},
        {key:'het gebeurt', value: 'het gebeurt'},
        {key:'uw', value: 'uw'},
        {key:'de sneeuwpop', value: 'de sneeuwpop'},
        {key:'opnieuw', value: 'opnieuw'},
        {key:'hij geeuwt', value: 'hij geeuwt'},
        {key:'hij schreeuwt', value: 'hij schreeuwt'},
        {key:'fraai', value: 'fraai'},
        {key:'saai', value: 'saai'},
        {key:'het waait', value: 'het waait'},
        {key:'mooi', value: 'mooi'},
        {key:'nooit', value: 'nooit'},
        {key:'hij strooit', value: 'hij strooit'},
        {key:'oei', value: 'oei'},
        {key:'hij bemoeit zich', value: 'hij bemoeit zich'},
        {key:'het bloeit', value: 'het bloeit'},
        {key:'hij loeit', value: 'hij loeit'},
        {key:'blauw', value: 'blauw'},
        {key:'flauw', value: 'flauw'},
        {key:'gauw', value: 'gauw'},
        {key:'hij snauwt', value: 'hij snauwt'},
        {key:'het gebouw', value: 'het gebouw'},
        {key:'nou', value: 'nou'},
        {key:'ik hou', value: 'ik hou'},
        {key:'hij vertrouwt', value: 'hij vertrouwt'},
        {key:'zij zou', value: 'zij zou'},
        {key:'de baard', value: 'de baard'},
        {key:'het bed', value: 'het bed'},
        {key:'het geld', value: 'het geld'},
        {key:'de hand', value: 'de hand'},
        {key:'de hoed', value: 'de hoed'},
        {key:'de hond', value: 'de hond'},
        {key:'het hoofd', value: 'het hoofd'},
        {key:'het kind', value: 'het kind'},
        {key:'de mond', value: 'de mond'},
        {key:'de vriend', value: 'de vriend'},
        {key:'de fout', value: 'de fout'},
        {key:'de kaart', value: 'de kaart'},
        {key:'de kast', value: 'de kast'},
        {key:'de kist', value: 'de kist'},
        {key:'de klant', value: 'de klant'},
        {key:'de poot', value: 'de poot'},
        {key:'de snuit', value: 'de snuit'},
        {key:'de staart', value: 'de staart'},
        {key:'de straat', value: 'de straat'},
        {key:'blind', value: 'blind'},
        {key:'de brand', value: 'de brand'},
        {key:'het geluid', value: 'het geluid'},
        {key:'goed', value: 'goed'},
        {key:'hard', value: 'hard'},
        {key:'kwaad', value: 'kwaad'},
        {key:'rood', value: 'rood'},
        {key:'verliefd', value: 'verliefd'},
        {key:'vreemd', value: 'vreemd'},
        {key:'wild', value: 'wild'},
        {key:'het gat', value: 'het gat'},
        {key:'groot', value: 'groot'},
        {key:'het hart', value: 'het hart'},
        {key:'heet', value: 'heet'},
        {key:'nat', value: 'nat'},
        {key:'de sloot', value: 'de sloot'},
        {key:'wit', value: 'wit'},
        {key:'woest', value: 'woest'},
        {key:'de zeilboot', value: 'de zeilboot'},
        {key:'zwart', value: 'zwart'},
        {key:'de keizer', value: 'de keizer'},
        {key:'het eiland', value: 'het eiland'},
        {key:'de pleister', value: 'de pleister'},
        {key:'het geheim', value: 'het geheim'},
        {key:'eigen', value: 'eigen'},
        {key:'hij eist', value: 'hij eist'},
        {key:'de meid', value: 'de meid'},
        {key:'het weiland', value: 'het weiland'},
        {key:'het eind', value: 'het eind'},
        {key:'de aardbei', value: 'de aardbei'},
        {key:'altijd', value: 'altijd'},
        {key:'het bedrijf', value: 'het bedrijf'},
        {key:'dichtbij', value: 'dichtbij'},
        {key:'het gordijn', value: 'het gordijn'},
        {key:'de leeftijd', value: 'de leeftijd'},
        {key:'de lijst', value: 'de lijst'},
        {key:'het ontbijt', value: 'het ontbijt'},
        {key:'wijd', value: 'wijd'},
        {key:'het spijt mij', value: 'het spijt mij'},
        {key:'hij verdwijnt', value: 'hij verdwijnt'},
        {key:'de aarde', value: 'de aarde'},
        {key:'beste', value: 'beste'},
        {key:'de derde', value: 'de derde'},
        {key:'kleine', value: 'kleine'},
        {key:'de lente', value: 'de lente'},
        {key:'leuke', value: 'leuke'},
        {key:'sterke', value: 'sterke'},
        {key:'de tante', value: 'de tante'},
        {key:'de verte', value: 'de verte'},
        {key:'zwarte', value: 'zwarte'},
        {key:'buiten', value: 'buiten'},
        {key:'de keuken', value: 'de keuken'},
        {key:'de morgen', value: 'de morgen'},
        {key:'het noorden', value: 'het noorden'},
        {key:'het oosten', value: 'het oosten'},
        {key:'het westen', value: 'het westen'},
        {key:'het zuiden', value: 'het zuiden'},
        {key:'buigen', value: 'buigen'},
        {key:'knijpen', value: 'knijpen'},
        {key:'snurken', value: 'snurken'},
        {key:'de deksel', value: 'de deksel'},
        {key:'de duivel', value: 'de duivel'},
        {key:'de heuvel', value: 'de heuvel'},
        {key:'het meubel', value: 'het meubel'},
        {key:'de sleutel', value: 'de sleutel'},
        {key:'de spiegel', value: 'de spiegel'},
        {key:'de vleugel', value: 'de vleugel'},
        {key:'de wortel', value: 'de wortel'},
        {key:'de bliksem', value: 'de bliksem'},
        {key:'stiekem', value: 'stiekem'},
        {key:'de ander', value: 'de ander'},
        {key:'donker', value: 'donker'},
        {key:'de moeder', value: 'de moeder'},
        {key:'het monster', value: 'het monster'},
        {key:'onder', value: 'onder'},
        {key:'verder', value: 'verder'},
        {key:'vroeger', value: 'vroeger'},
        {key:'de winter', value: 'de winter'},
        {key:'de zolder', value: 'de zolder'},
        {key:'zonder', value: 'zonder'},
        {key:'bekend', value: 'bekend'},
        {key:'beroemd', value: 'beroemd'},
        {key:'het beroep', value: 'het beroep'},
        {key:'beslist', value: 'beslist'},
        {key:'hij beschermt', value: 'hij beschermt'},
        {key:'hij bestaat', value: 'hij bestaat'},
        {key:'hij betaalt', value: 'hij betaalt'},
        {key:'het gebied', value: 'het gebied'},
        {key:'het gesprek', value: 'het gesprek'},
        {key:'het gevaar', value: 'het gevaar'},
        {key:'het gevoel', value: 'het gevoel'},
        {key:'het gezin', value: 'het gezin'},
        {key:'gezond', value: 'gezond'},
        {key:'hij gelooft', value: 'hij gelooft'},
        {key:'verbaasd', value: 'verbaasd'},
        {key:'het verkeer', value: 'het verkeer'},
        {key:'hij verdeelt', value: 'hij verdeelt'},
        {key:'hij vergeet', value: 'hij vergeet'},
        {key:'hij verkoopt', value: 'hij verkoopt'},
        {key:'hij  verzint', value: 'hij  verzint'},
        {key:'anders', value: 'anders'},
        {key:'de dokter', value: 'de dokter'},
        {key:'eerder', value: 'eerder'},
        {key:'elke', value: 'elke'},
        {key:'ergens', value: 'ergens'},
        {key:'de groente', value: 'de groente'},
        {key:'de hamster', value: 'de hamster'},
        {key:'de laatste', value: 'de laatste'},
        {key:'de marmot', value: 'de marmot'},
        {key:'de meeste', value: 'de meeste'},
        {key:'minder', value: 'minder'},
        {key:'nergens', value: 'nergens'},
        {key:'paarse', value: 'paarse'},
        {key:'de schilder', value: 'de schilder'},
        {key:'sterker', value: 'sterker'},
        {key:'telkens', value: 'telkens'},
        {key:'verse', value: 'verse'},
        {key:'vreemde', value: 'vreemde'},
        {key:'warme', value: 'warme'},
        {key:'welke', value: 'welke'},
        {key:'de boeken', value: 'de boeken'},
        {key:'bruine', value: 'bruine'},
        {key:'goede', value: 'goede'},
        {key:'groene', value: 'groene'},
        {key:'de groepen', value: 'de groepen'},
        {key:'ieder', value: 'ieder'},
        {key:'de kleuter', value: 'de kleuter'},
        {key:'het kuiken', value: 'het kuiken'},
        {key:'liever', value: 'liever'},
        {key:'de schoenen', value: 'de schoenen'},
        {key:'schuine', value: 'schuine'},
        {key:'de woede', value: 'de woede'},
        {key:'zoete', value: 'zoete'},
        {key:'huilen', value: 'huilen'},
        {key:'krijgen', value: 'krijgen'},
        {key:'kijken', value: 'kijken'},
        {key:'liegen', value: 'liegen'},
        {key:'roepen', value: 'roepen'},
        {key:'ruilen', value: 'ruilen'},
        {key:'zoeken', value: 'zoeken'},
        {key:'ermee', value: 'ermee'},
        {key:'de landweg', value: 'de landweg'},
        {key:'linksaf', value: 'linksaf'},
        {key:'naartoe', value: 'naartoe'},
        {key:'omlaag', value: 'omlaag'},
        {key:'het ontwerp', value: 'het ontwerp'},
        {key:'het onweer', value: 'het onweer'},
        {key:'de oorzaak', value: 'de oorzaak'},
        {key:'opeens', value: 'opeens'},
        {key:'de opzet', value: 'de opzet'},
        {key:'rechtdoor', value: 'rechtdoor'},
        {key:'de snelweg', value: 'de snelweg'},
        {key:'het stoomschip', value: 'het stoomschip'},
        {key:'de stoomtrein', value: 'de stoomtrein'},
        {key:'het stoplicht', value: 'het stoplicht'},
        {key:'het vliegtuig', value: 'het vliegtuig'},
        {key:'het vliegveld', value: 'het vliegveld'},
        {key:'vooraan', value: 'vooraan'},
        {key:'voorbij', value: 'voorbij'},
        {key:'de voorrang', value: 'de voorrang'},
        {key:'later', value: 'later'},
        {key:'de namen', value: 'de namen'},
        {key:'rare', value: 'rare'},
        {key:'samen', value: 'samen'},
        {key:'de tranen', value: 'de tranen'},
        {key:'plagen', value: 'plagen'},
        {key:'beter', value: 'beter'},
        {key:'deze', value: 'deze'},
        {key:'even', value: 'even'},
        {key:'de ezel', value: 'de ezel'},
        {key:'zeker', value: 'zeker'},
        {key:'hoge', value: 'hoge'},
        {key:'open', value: 'open'},
        {key:'over', value: 'over'},
        {key:'rode', value: 'rode'},
        {key:'de zomer', value: 'de zomer'},
        {key:'de buren', value: 'de buren'},
        {key:'de muziek', value: 'de muziek'},
        {key:'de ruzie', value: 'de ruzie'},
        {key:'de uren', value: 'de uren'},
        {key:'bijna', value: 'bijna'},
        {key:'ha', value: 'ha'},
        {key:'hoera', value: 'hoera'},
        {key:'ja', value: 'ja'},
        {key:'na', value: 'na'},
        {key:'de oma', value: 'de oma'},
        {key:'de opa', value: 'de opa'},
        {key:'de sla', value: 'de sla'},
        {key:'de foto', value: 'de foto'},
        {key:'ho', value: 'ho'},
        {key:'hoezo', value: 'hoezo'},
        {key:'het stro', value: 'het stro'},
        {key:'zo', value: 'zo'},
        {key:'nu', value: 'nu'},
        {key:'u', value: 'u'},
        {key:'mee', value: 'mee'},
        {key:'nee', value: 'nee'},
        {key:'de slee', value: 'de slee'},
        {key:'twee', value: 'twee'},
        {key:'de zee', value: 'de zee'},
        {key:'de dauw', value: 'de dauw'},
        {key:'de auto', value: 'de auto'},
        {key:'miauwt', value: 'miauwt'},
        {key:'de wenkbrauw', value: 'de wenkbrauw'},
        {key:'rauw', value: 'rauw'},
        {key:'grauw', value: 'grauw'},
        {key:'benauwd', value: 'benauwd'},
        {key:'de pauze', value: 'de pauze'},
        {key:'lauwe', value: 'lauwe'},
        {key:'de saus', value: 'de saus'},
        {key:'de buurvrouw', value: 'de buurvrouw'},
        {key:'de fouten', value: 'de fouten'},
        {key:'de inhoud', value: 'de inhoud'},
        {key:'de mevrouw', value: 'de mevrouw'},
        {key:'het oerwoud', value: 'het oerwoud'},
        {key:'oud', value: 'oud'},
        {key:'ouders', value: 'ouders'},
        {key:'de schouder', value: 'de schouder'},
        {key:'houden', value: 'houden'},
        {key:'trouwen', value: 'trouwen'},
        {key:'alleen', value: 'alleen'},
        {key:'hallo', value: 'hallo'},
        {key:'wakker', value: 'wakker'},
        {key:'wanneer', value: 'wanneer'},
        {key:'de herrie', value: 'de herrie'},
        {key:'lekker', value: 'lekker'},
        {key:'de letter', value: 'de letter'},
        {key:'bellen', value: 'bellen'},
        {key:'de kikker', value: 'de kikker'},
        {key:'de middag', value: 'de middag'},
        {key:'liggen', value: 'liggen'},
        {key:'zitten', value: 'zitten'},
        {key:'de koffer', value: 'de koffer'},
        {key:'de koffie', value: 'de koffie'},
        {key:'de trommel', value: 'de trommel'},
        {key:'stoppen', value: 'stoppen'},
        {key:'jullie', value: 'jullie'},
        {key:'het nummer', value: 'het nummer'},
        {key:'tussen', value: 'tussen'},
        {key:'zullen', value: 'zullen'},
        {key:'de kamer', value: 'de kamer'},
        {key:'de manier', value: 'de manier'},
        {key:'het water', value: 'het water'},
        {key:'laten', value: 'laten'},
        {key:'praten', value: 'praten'},
        {key:'de hemel', value: 'de hemel'},
        {key:'negen', value: 'negen'},
        {key:'zeven', value: 'zeven'},
        {key:'spelen', value: 'spelen'},
        {key:'boven', value: 'boven'},
        {key:'de motor', value: 'de motor'},
        {key:'de vogel', value: 'de vogel'},
        {key:'komen', value: 'komen'},
        {key:'stromen', value: 'stromen'},
        {key:'de vuren', value: 'de vuren'},
        {key:'zure', value: 'zure'},
        {key:'duren', value: 'duren'},
        {key:'sturen', value: 'sturen'},
        {key:'turen', value: 'turen'},
        {key:'de haai', value: 'de haai'},
        {key:'het lawaai', value: 'het lawaai'},
        {key:'aaien', value: 'aaien'},
        {key:'draaien', value: 'draaien'},
        {key:'kraaien', value: 'kraaien'},
        {key:'zwaaien', value: 'zwaaien'},
        {key:'de fooi', value: 'de fooi'},
        {key:'het hooi', value: 'het hooi'},
        {key:'mooiste', value: 'mooiste'},
        {key:'de prooi', value: 'de prooi'},
        {key:'de rotzooi', value: 'de rotzooi'},
        {key:'gooien', value: 'gooien'},
        {key:'foei', value: 'foei'},
        {key:'het geknoei', value: 'het geknoei'},
        {key:'de gloeilamp', value: 'de gloeilamp'},
        {key:'de koeien', value: 'de koeien'},
        {key:'de moeite', value: 'de moeite'},
        {key:'knoeien', value: 'knoeien'},
        {key:'snoeien', value: 'snoeien'},
        {key:'stoeien', value: 'stoeien'},
        {key:'de beren', value: 'de beren'},
        {key:'de keren', value: 'de keren'},
        {key:'de kleren', value: 'de kleren'},
        {key:'de meren', value: 'de meren'},
        {key:'de speren', value: 'de speren'},
        {key:'de veren', value: 'de veren'},
        {key:'leren', value: 'leren'},
        {key:'smeren', value: 'smeren'},
        {key:'de oren', value: 'de oren'},
        {key:'de sporen', value: 'de sporen'},
        {key:'boren', value: 'boren'},
        {key:'horen', value: 'horen'},
        {key:'storen', value: 'storen'},
        {key:'de deuren', value: 'de deuren'},
        {key:'de kleuren', value: 'de kleuren'},
        {key:'de scheuren', value: 'de scheuren'},
        {key:'sleuren', value: 'sleuren'},
        {key:'speuren', value: 'speuren'},
        {key:'treuren', value: 'treuren'},
        {key:'zeuren', value: 'zeuren'},
        {key:'bange', value: 'bange'},
        {key:'de gangen', value: 'de gangen'},
        {key:'de hanger', value: 'de hanger'},
        {key:'de hengel', value: 'de hengel'},
        {key:'jonge', value: 'jonge'},
        {key:'de jongen', value: 'de jongen'},
        {key:'de lengte', value: 'de lengte'},
        {key:'de slinger', value: 'de slinger'},
        {key:'de vinger', value: 'de vinger'},
        {key:'dronken', value: 'dronken'},
        {key:'de enkel', value: 'de enkel'},
        {key:'flinke', value: 'flinke'},
        {key:'slanke', value: 'slanke'},
        {key:'de winkel', value: 'de winkel'},
        {key:'hinken', value: 'hinken'},
        {key:'janken', value: 'janken'},
        {key:'de botsing', value: 'de botsing'},
        {key:'de koning', value: 'de koning'},
        {key:'de staking', value: 'de staking'},
        {key:'de woning', value: 'de woning'},
        {key:'de afstand', value: 'de afstand'},
        {key:'de avond', value: 'de avond'},
        {key:'breed', value: 'breed'},
        {key:'het geluid', value: 'het geluid'},
        {key:'koud', value: 'koud'},
        {key:'het strand', value: 'het strand'},
        {key:'verkeerd', value: 'verkeerd'},
        {key:'de wind', value: 'de wind'},
        {key:'het zand', value: 'het zand'},
        {key:'de zeehond', value: 'de zeehond'},
        {key:'geschikt', value: 'geschikt'},
        {key:'de hut', value: 'de hut'},
        {key:'kapot', value: 'kapot'},
        {key:'de landkaart', value: 'de landkaart'},
        {key:'het moment', value: 'het moment'},
        {key:'de plaat', value: 'de plaat'},
        {key:'het riet', value: 'het riet'},
        {key:'de rust', value: 'de rust'},
        {key:'de sloot', value: 'de sloot'},
        {key:'want', value: 'want'},
        {key:'het eendje', value: 'het eendje'},
        {key:'een eindje', value: 'een eindje'},
        {key:'het grapje', value: 'het grapje'},
        {key:'het kunstje', value: 'het kunstje'},
        {key:'het plekje', value: 'het plekje'},
        {key:'een poosje', value: 'een poosje'},
        {key:'een stukje', value: 'een stukje'},
        {key:'een tijdje', value: 'een tijdje'},
        {key:'een ijsje', value: 'een ijsje'},
        {key:'het visje', value: 'het visje'},
        {key:'een beetje', value: 'een beetje'},
        {key:'het meisje', value: 'het meisje'},
        {key:'het boompje', value: 'het boompje'},
        {key:'het geheimpje', value: 'het geheimpje'},
        {key:'het raampje', value: 'het raampje'},
        {key:'het buitje', value: 'het buitje'},
        {key:'het broertje', value: 'het broertje'},
        {key:'het diertje', value: 'het diertje'},
        {key:'het eitje', value: 'het eitje'},
        {key:'een uurtje', value: 'een uurtje'},
        {key:'aardig', value: 'aardig'},
        {key:'bezig', value: 'bezig'},
        {key:'giftig', value: 'giftig'},
        {key:'grappig', value: 'grappig'},
        {key:'handig', value: 'handig'},
        {key:'lastig', value: 'lastig'},
        {key:'nodig', value: 'nodig'},
        {key:'rustig', value: 'rustig'},
        {key:'twintig', value: 'twintig'},
        {key:'zuinig', value: 'zuinig'},
        {key:'eerlijk', value: 'eerlijk'},
        {key:'gevaarlijk', value: 'gevaarlijk'},
        {key:'heerlijk', value: 'heerlijk'},
        {key:'kwalijk', value: 'kwalijk'},
        {key:'lelijk', value: 'lelijk'},
        {key:'moeilijk', value: 'moeilijk'},
        {key:'natuurlijk', value: 'natuurlijk'},
        {key:'pijnlijk', value: 'pijnlijk'},
        {key:'sierlijk', value: 'sierlijk'},
        {key:'vrolijk', value: 'vrolijk'},
        {key:'de autopech', value: 'de autopech'},
        {key:'het gelach', value: 'het gelach'},
        {key:'de kachel', value: 'de kachel'},
        {key:'het lichaam', value: 'het lichaam'},
        {key:'och', value: 'och'},
        {key:'juichen', value: 'juichen'},
        {key:'lachen', value: 'lachen'},
        {key:'achter', value: 'achter'},
        {key:'het bericht', value: 'het bericht'},
        {key:'dichtbij', value: 'dichtbij'},
        {key:'de ochtend', value: 'de ochtend'},
        {key:'de opdracht', value: 'de opdracht'},
        {key:'prachtig', value: 'prachtig'},
        {key:'rechter', value: 'rechter'},
        {key:'rechtop', value: 'rechtop'},
        {key:'slechte', value: 'slechte'},
        {key:'vannacht', value: 'vannacht'},
        {key:'vechten', value: 'vechten'},
        {key:'vluchten', value: 'vluchten'},
        {key:'wachten', value: 'wachten'},
        {key:'de boeven', value: 'de boeven'},
        {key:'de brieven', value: 'de brieven'},
        {key:'de dieven', value: 'de dieven'},
        {key:'lieve', value: 'lieve'},
        {key:'blijven', value: 'blijven'},
        {key:'geven', value: 'geven'},
        {key:'hoeven', value: 'hoeven'},
        {key:'leven', value: 'leven'},
        {key:'schrijven', value: 'schrijven'},
        {key:'verven', value: 'verven'},
        {key:'boze', value: 'boze'},
        {key:'grijze', value: 'grijze'},
        {key:'de huizen', value: 'de huizen'},
        {key:'de keuze', value: 'de keuze'},
        {key:'onze', value: 'onze'},
        {key:'de prijzen', value: 'de prijzen'},
        {key:'de rozen', value: 'de rozen'},
        {key:'kiezen', value: 'kiezen'},
        {key:'lezen', value: 'lezen'},
        {key:'wijzen', value: 'wijzen'},
        {key:'de krab', value: 'de krab'},
        {key:'de slab', value: 'de slab'},
        {key:'het web', value: 'het web'},
        {key:'ik heb', value: 'ik heb'},
        {key:'ik krab', value: 'ik krab'},
        {key:'de hap', value: 'de hap'},
        {key:'de klap', value: 'de klap'},
        {key:'de knoop', value: 'de knoop'},
        {key:'slop', value: 'slop'},
        {key:'de trap', value: 'de trap'},
        {key:'de held', value: 'de held'},
        {key:'iemand', value: 'iemand'},
        {key:'het lied', value: 'het lied'},
        {key:'niemand', value: 'niemand'},
        {key:'het woord', value: 'het woord'},
        {key:'apart', value: 'apart'},
        {key:'onverwacht', value: 'onverwacht'},
        {key:'het portret', value: 'het portret'},
        {key:'de tekst', value: 'de tekst'},
        {key:'het tijdschrift', value: 'het tijdschrift'},
        {key:'ruwe', value: 'ruwe'},
        {key:'de schaduw', value: 'de schaduw'},
        {key:'schuwe', value: 'schuwe'},
        {key:'sluwe', value: 'sluwe'},
        {key:'de zwaluw', value: 'de zwaluw'},
        {key:'duwen', value: 'duwen'},
        {key:'waarschuwen', value: 'waarschuwen'},
        {key:'eeuwenlang', value: 'eeuwenlang'},
        {key:'eeuwig', value: 'eeuwig'},
        {key:'de leeuwen', value: 'de leeuwen'},
        {key:'de sneeuwbal', value: 'de sneeuwbal'},
        {key:'de sneeuwvlok', value: 'de sneeuwvlok'},
        {key:'de spreeuw', value: 'de spreeuw'},
        {key:'geeuwen', value: 'geeuwen'},
        {key:'schreeuwen', value: 'schreeuwen'},
        {key:'sneeuwen', value: 'sneeuwen'},
        {key:'benieuwd', value: 'benieuwd'},
        {key:'nieuwe', value: 'nieuwe'},
        {key:'de nieuwslezer', value: 'de nieuwslezer'},
        {key:'het nieuwtje', value: 'het nieuwtje'}
    ],

	chemSymbols: [
		{key:'Ac', value: 'Actinium'},
		{key:'Ag', value: 'Silver'},
		{key:'Al', value: 'Aluminium'},
		{key:'Am', value: 'Americium'},
		{key:'Ar', value: 'Argon'},
		{key:'As', value: 'Arsenic'},
		{key:'At', value: 'Astatine'},
		{key:'Au', value: 'Gold'},
		{key:'B', value: 'Boron'},
		{key:'Ba', value: 'Barium'},
		{key:'Be', value: 'Beryllium'},
		{key:'Bh', value: 'Bohrium'},
		{key:'Bi', value: 'Bismuth'},
		{key:'Bk', value: 'Berkelium'},
		{key:'Br', value: 'Bromine'},
		{key:'C', value: 'Carbon'},
		{key:'Ca', value: 'Calcium'},
		{key:'Cd', value: 'Cadmium'},
		{key:'Ce', value: 'Cerium'},
		{key:'Cf', value: 'Californium'},
		{key:'Cl', value: 'Chlorine'},
		{key:'Cm', value: 'Curium'},
		{key:'Cn', value: 'Copernicium'},
		{key:'Co', value: 'Cobalt'},
		{key:'Cr', value: 'Chromium'},
		{key:'Cs', value: 'Caesium'},
		{key:'Cu', value: 'Copper'},
		{key:'Db', value: 'Dubnium'},
		{key:'Ds', value: 'Darmstadtium'},
		{key:'Dy', value: 'Dysprosium'},
		{key:'Er', value: 'Erbium'},
		{key:'Es', value: 'Einsteinium'},
		{key:'Eu', value: 'Europium'},
		{key:'F', value: 'Fluorine'},
		{key:'Fe', value: 'Iron'},
		{key:'Fl', value: 'Flerovium'},
		{key:'Fm', value: 'Fermium'},
		{key:'Fr', value: 'Francium'},
		{key:'Ga', value: 'Gallium'},
		{key:'Gd', value: 'Gadolinium'},
		{key:'Ge', value: 'Germanium'},
		{key:'H', value: 'Hydrogen'},
		{key:'He', value: 'Helium'},
		{key:'Hf', value: 'Hafnium'},
		{key:'Hg', value: 'Mercury'},
		{key:'Ho', value: 'Holmium'},
		{key:'Hs', value: 'Hassium'},
		{key:'I', value: 'Iodine'},
		{key:'In', value: 'Indium'},
		{key:'Ir', value: 'Iridium'},
		{key:'K', value: 'Potassium'},
		{key:'Kr', value: 'Krypton'},
		{key:'La', value: 'Lanthanum'},
		{key:'Li', value: 'Lithium'},
		{key:'Lr', value: 'Lawrencium'},
		{key:'Lu', value: 'Lutetium'},
		{key:'Lv', value: 'Livermorium'},
		{key:'Md', value: 'Mendelevium'},
		{key:'Mg', value: 'Magnesium'},
		{key:'Mn', value: 'Manganese'},
		{key:'Mo', value: 'Molybdenum'},
		{key:'Mt', value: 'Meitnerium'},
		{key:'N', value: 'Nitrogen'},
		{key:'Na', value: 'Sodium'},
		{key:'Nb', value: 'Niobium'},
		{key:'Nd', value: 'Neodymium'},
		{key:'Ne', value: 'Neon'},
		{key:'Ni', value: 'Nickel'},
		{key:'No', value: 'Nobelium'},
		{key:'Np', value: 'Neptunium'},
		{key:'O', value: 'Oxygen'},
		{key:'Os', value: 'Osmium'},
		{key:'P', value: 'Phosphorus'},
		{key:'Pa', value: 'Protactinium'},
		{key:'Pb', value: 'Lead'},
		{key:'Pd', value: 'Palladium'},
		{key:'Pm', value: 'Promethium'},
		{key:'Po', value: 'Polonium'},
		{key:'Pr', value: 'Praseodymium'},
		{key:'Pt', value: 'Platinum'},
		{key:'Pu', value: 'Plutonium'},
		{key:'Ra', value: 'Radium'},
		{key:'Rb', value: 'Rubidium'},
		{key:'Re', value: 'Rhenium'},
		{key:'Rf', value: 'Rutherfordium'},
		{key:'Rg', value: 'Roentgenium'},
		{key:'Rh', value: 'Rhodium'},
		{key:'Rn', value: 'Radon'},
		{key:'Ru', value: 'Ruthenium'},
		{key:'S', value: 'Sulfur'},
		{key:'Sb', value: 'Antimony'},
		{key:'Sc', value: 'Scandium'},
		{key:'Se', value: 'Selenium'},
		{key:'Sg', value: 'Seaborgium'},
		{key:'Si', value: 'Silicon'},
		{key:'Sm', value: 'Samarium'},
		{key:'Sn', value: 'Tin'},
		{key:'Sr', value: 'Strontium'},
		{key:'Ta', value: 'Tantalum'},
		{key:'Tb', value: 'Terbium'},
		{key:'Tc', value: 'Technetium'},
		{key:'Te', value: 'Tellurium'},
		{key:'Th', value: 'Thorium'},
		{key:'Ti', value: 'Titanium'},
		{key:'Tl', value: 'Thallium'},
		{key:'Tm', value: 'Thulium'},
		{key:'U', value: 'Uranium'},
		{key:'Uuo', value: 'Ununoctium'},
		{key:'Uup', value: 'Ununpentium'},
		{key:'Uus', value: 'Ununseptium'},
		{key:'Uut', value: 'Ununtrium'},
		{key:'V', value: 'Vanadium'},
		{key:'W', value: 'Tungsten'},
		{key:'Xe', value: 'Xenon'},
		{key:'Y', value: 'Yttrium'},
		{key:'Yb', value: 'Ytterbium'},
		{key:'Zn', value: 'Zinc'},
		{key:'Zr', value: 'Zirconium'}
	],

	spanishWords: [
		{key:'escuela', value:'school'},
		{key:'manzana', value:'apple'},
		{key:'mesa', value:'table'},
		{key:'verde', value:'green'},
		{key:'nariz', value:'nose'},
		{key:'ciencia', value:'science'},
		{key:'biblioteca', value:'library'},
		{key:'médico', value:'doctor'},
		{key:'queso', value:'cheese'},
		{key:'puerta', value:'door'},
		{key:'coche', value:'car'},
		{key:'árbol', value:'tree'},
		{key:'playa', value:'beach'},
		{key:'brazo', value:'arm'},
		{key:'perro', value:'dog'},
		{key:'maestro', value:'teacher'},
		{key:'ojo', value:'eye'},
		{key:'ventana', value:'window'},
		{key:'azul', value:'blue'},
		{key:'rojo', value:'red'},
		{key:'gato', value:'cat'},
		{key:'libro', value:'book'},
		{key:'amarillo', value:'yellow'},
		{key:'blanco', value:'white'},
		{key:'boca', value:'mouth'},
		{key:'cabeza', value:'head'}
	]
};
